### ISSUE TITLE
[ERROR] An error occurred while retrieving information for the 'PngInfo' node.

### ISSUE THREAD

**Issue by endege** [ltdrdata/ComfyUI-Manager#1197]
I ran an Update All and now I'm getting this error, any ideas?

```
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'PngInfo' node.
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'PngInfo' has no attribute 'INPUT_TYPES'
```

**Comment by endege** [comment]
Did a fresh install of ComfyUI & ComfyUI Manager and issue got resolved, though I can't say I found the node that was causing this issue.
