### ISSUE TITLE
今日更新，这个老问题，还在，没有解决!!!!!

### ISSUE THREAD

**Issue by goodluck821** [ltdrdata/ComfyUI-Manager#1213]
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1339, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1336, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1323, in get_cache
    json_obj = await core.get_data(uri, True)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 620, in get_data
    async with session.get(uri) as resp:
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
K:\ComfyUI-aki-v1.4\python\lib\site-packages\albumentations\check_version.py:51: UserWarning: Error fetching version info <urlopen error _ssl.c:990: The handshake operation timed out>
  data = fetch_version_info()

**Comment by goodluck821** [comment]
https://[raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/](https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/)
400: Invalid request

**Comment by ltdrdata** [comment]
That is an issue with your network environment. 
While this issue will be updated later to support reverse proxy, for now you need to use a VPN.

https://github.com/ltdrdata/ComfyUI-Manager/pull/795
