### ISSUE TITLE
Error with starting comfyui-mananger

### ISSUE THREAD

**Issue by goodluck821** [ltdrdata/ComfyUI-Manager#1228]
### ComfyUI Revision: 2798 [65a86591] | Released on '2024-10-29'
K:\ComfyUI-aki-v1.4\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(

Exception in thread Thread-9 (<lambda>):
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1339, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1336, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1323, in get_cache
    json_obj = await core.get_data(uri, True)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 627, in get_data
    json_obj = json.loads(json_text)
  File "K:\ComfyUI-aki-v1.4\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "K:\ComfyUI-aki-v1.4\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "K:\ComfyUI-aki-v1.4\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

**Comment by ltdrdata** [comment]
A temporary issue may have occurred during the DB update process.
Please check if you're still experiencing the same issue.

**Comment by goodluck821** [comment]
Not often,just these days.

**Comment by goodluck821** [comment]
Thanks a lot!
