### ISSUE TITLE
Today updated comfyui-mananger

### ISSUE THREAD

**Issue by goodluck821** [ltdrdata/ComfyUI-Manager#1230]
Loading: ComfyUI-Manager (V2.51.9)
 ComfyUI Revision: 2798 [65a86591] | Released on '2024-10-29'
Exception in thread Thread-9 (<lambda>):
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 1317, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 971, in _resolve_host
    return await asyncio.shield(resolved_host_task)
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 1002, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\resolver.py", line 38, in resolve
    infos = await self._loop.getaddrinfo(
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "K:\ComfyUI-aki-v1.4\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "K:\ComfyUI-aki-v1.4\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1339, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1336, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1323, in get_cache
    json_obj = await core.get_data(uri, True)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 620, in get_data
    async with session.get(uri) as resp:
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\client.py", line 663, in _request
    conn = await self._connector.connect(
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "K:\ComfyUI-aki-v1.4\python\lib\site-packages\aiohttp\connector.py", line 1323, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]

**Comment by goodluck821** [comment]
![屏幕截图 2024-11-10 203616](https://github.com/user-attachments/assets/9b2d47f4-a9b6-4c8d-bb2c-30de1a8157f8)

**Comment by goodluck821** [comment]
![Uploading 屏幕截图 2024-11-10 203858.jpg…]()

**Comment by ltdrdata** [comment]
Try this url: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/refs/heads/main/custom-node-list.json

**Comment by goodluck821** [comment]
Traceback (most recent call last):
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "K:\ComfyUI-aki-v1.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1343, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "K:\ComfyUI-aki-v1.4\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1340, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1327, in get_cache
    json_obj = await core.get_data(uri, True)
  File "K:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 628, in get_data
    json_obj = json.loads(json_text)
  File "K:\ComfyUI-aki-v1.4\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "K:\ComfyUI-aki-v1.4\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "K:\ComfyUI-aki-v1.4\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

Now,like this.

**Comment by goodluck821** [comment]
OK1
