### ISSUE TITLE
Error is attached: "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4249 column 9 (char 210788) " Puzzeled on how to fix it.

### ISSUE THREAD

**Issue by CybereDrum** [ltdrdata/ComfyUI-Manager#333]
### Mixlab Nodes: Loaded
LaMaInpainting.available True
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Exception in thread Thread-15 (<lambda>):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2257, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2255, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 2243, in get_cache
    json_obj = await get_data(uri)
               ^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 530, in get_data
    json_obj = json.loads(json_text)
               ^^^^^^^^^^^^^^^^^^^^^
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4249 column 9 (char 210788)
ClipInterrogator.available True

**Comment by ltdrdata** [comment]
Sorry... This is fixed.

**Comment by CybereDrum** [comment]
Now worries, checked it now again. Thanks :)
